import { jsx as _jsx, Fragment as _Fragment, jsxs as _jsxs } from "react/jsx-runtime";
import { Footer } from '../components/Footer';
import { Header } from '../components/Header';
import { usePathJoin } from '../hooks/usePathJoin';
const render = (data) => {
    const { canonical, children, description, metadata, ogImage, ogType, page, title, } = data;
    return (_jsxs("html", { lang: metadata?.lang || 'ja', className: "no-js", children: [_jsxs("head", { children: [_jsx("meta", { charSet: metadata?.encoding || 'utf-8' }), _jsx("meta", { name: "viewport", content: "width=device-width, initial-scale=1.0, viewport-fit=cover" }), _jsx("meta", { name: "format-detection", content: "telephone=no" }), _jsx("meta", { name: "theme-color", content: "#ffffff" }), _jsx("title", { children: title }), _jsx("meta", { name: "description", content: description || metadata?.description || '' }), _jsx("meta", { property: "og:locale", content: "ja_JP" }), _jsx("meta", { property: "og:type", content: ogType || 'article' }), _jsx("meta", { property: "og:title", content: title }), _jsx("meta", { property: "og:description", content: description || metadata?.description || '' }), _jsx("meta", { property: "og:url", content: usePathJoin(metadata?.siteUrl || '', page?.url || canonical || '/') }), _jsx("meta", { property: "og:site_name", content: metadata?.site_name }), metadata?.siteUrl && (_jsx("meta", { property: "og:image", content: usePathJoin(metadata?.siteUrl, ogImage || metadata?.ogImage || '') })), _jsx("meta", { name: "twitter:card", content: "summary_large_image" }), metadata?.twitterSite && (_jsx("meta", { name: "twitter:site", content: metadata?.twitterSite })), _jsx("link", { rel: "canonical", href: usePathJoin(metadata?.siteUrl || '', page?.url || canonical || '/') }), metadata?.webFonts && (_jsxs(_Fragment, { children: [_jsx("link", { rel: "preconnect", href: "https://fonts.googleapis.com" }), _jsx("link", { rel: "preconnect", href: "https://fonts.gstatic.com", crossOrigin: "" })] })), metadata?.webFonts?.map((url) => url?.path && (_jsx("link", { rel: "preload", as: "style", href: url?.path }, `fonts-preload-${url?.key}`))), metadata?.webFonts?.map((url) => url?.path && (_jsx("link", { rel: "stylesheet", href: url?.path }, `fonts-${url?.key}`))), _jsx("link", { rel: "stylesheet", href: "/src/main.css" }), _jsx("script", { type: "module", src: "/src/main.ts" })] }), _jsxs("body", { children: [_jsx(Header, {}), _jsx("main", { children: children }), _jsx(Footer, {})] })] }));
};
export default render;
